name:                servant-starter
version:             0.1.0.0
github:              "dougflip/servant-starter"
license:             BSD3
author:              "Doug DiFilippo"
maintainer:          "douglasdifilippo@gmail.com"
copyright:           "2018 Doug DiFilippo"

extra-source-files:
- readme.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/dougflip/servant-starter#readme>

# ghc-options: -Wall -Werror

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
      - servant
      - servant-client
      - aeson
      - http-client
      - http-client-tls

executables:
  servant-starter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-starter

tests:
  servant-starter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-starter
